Improve better understandable?

diff --git a/Gandalf/gandalf102 b/Gandalf/gandalf102
--- a/Gandalf/gandalf102
+++ b/Gandalf/gandalf102
@@ -4,7 +4,8 @@
 
 if [[ $EUID -ne 0 ]]; then
 
-   echo "ERROR: This needs root permissions. Since you are not logged in as root run 'su' (default password is 'alpine' - it's wise to change this) and then try again." 1>&2 
+   echo "ERROR: This script needs root permissions."
+   echo "Since you are not logged in as root run 'su' before. (Default password is 'alpine' - it's wise to change this) and then try again." 1>&2 
 
    exit 1
 
@@ -23,7 +24,8 @@ echo "Made by EthanRDoesMC and mehulrao."
 
 case $1 in
 "") 
-echo "USAGE: $0 hold: run directly after install of $GVERSIONNAME. It will prevent cydia from removing Gandalf automatically"
+echo "USAGE:"
+echo "$0 hold: run directly after install of $GVERSIONNAME. It will prevent cydia from removing Gandalf automatically"
 echo
 echo "$0 rmhold: run before update or uninstall to let cydia remove it."
  ;;
@@ -35,7 +37,10 @@ echo "$0 rmhold: run before update or uninstall to let cydia remove it."
  echo "$GVERSION install" | dpkg --set-selections
  ;;
  *)echo "ERROR: invalid parameter $1"
- echo "USAGE: $0 hold: run directly after install of $GVERSIONNAME. It will prevent cydia from removing Gandalf automatically"
- ;;
+ echo "USAGE:"
+ echo "$0 hold: run directly after install of $GVERSIONNAME. It will prevent cydia from removing Gandalf automatically"
+ echo
+echo "$0 rmhold: run before update or uninstall to let cydia remove it."
+;;
  esac
  echo "Thank you for using Gandalf."
